# PostgreSQL. Versions 12 and up are supported.
#
# Configure Using Conditions or Conditions Groups:
#   https://guides.rubyonrails.org/configuring.html#database-conditions
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "zen") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

development:
  <<: *default
  database: reasy_development

test:
  <<: *default
  database: reasy_test

production:
  primary: &production_default
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL", "postgresql://neondb_owner:npg_uKDiHxLq0Ne3@ep-wandering-salad-a7rmrq74-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require") %>
  cache:
    <<: *production_default
    migrations_paths: db/cache_migrate
    url: <%= URI.parse(ENV["DATABASE_URL"]).tap { |url| url.path += "_cache" } if ENV["DATABASE_URL"] %>
  queue:
    <<: *production_default
    migrations_paths: db/queue_migrate
    url: <%= URI.parse(ENV["DATABASE_URL"]).tap { |url| url.path += "_queue" } if ENV["DATABASE_URL"] %>
  cable:
    <<: *production_default
    migrations_paths: db/cable_migrate
    url: <%= URI.parse(ENV["DATABASE_URL"]).tap { |url| url.path += "_cable" } if ENV["DATABASE_URL"] %>
